### ISSUE TITLE
Question: was MVSNet running real-time?

### ISSUE THREAD

**Issue by ghost** [HKUST-Aerial-Robotics/DenseSurfelMapping#1]
Hi,

Could you explain if MVSDepthNet was running in real-time to generate the depth maps? If so, was it running on the drone?

Thanks! :)

**Comment by WANG-KX** [comment]
Dear,

Images are streamed to a laptop to estimate the depth maps in real-time. The laptop is an Alienware 17 with GTX1070.

Regards,
Kaixuan
