### ISSUE TITLE
vins-supported bug

### ISSUE THREAD

**Issue by liutao0913** [HKUST-Aerial-Robotics/DenseSurfelMapping#11]
感谢开源这么好的DenseSurfelMapping，在fusion_functions.cpp第208行
if (reference_frame_index - local_surfels[i].last_update >10 && local_surfels[i].update_times < 6)
其中10应为从launch文件中读取的drift_free_poses，不然保存的mesh有问题，谢谢！

**Comment by WANG-KX** [comment]
Hi,
这里的10只是我设置的一个阈值，应该和drift_free_poses没有什么关系。如果一个serfel在10次里面观测次数少于6次，就丢掉。
谢谢你的建议，最近我也在优化VINS版本，希望能进一步提升精度和效率。

**Comment by liutao0913** [comment]
Hi,非常感谢！
