### ISSUE TITLE
Some issue about sync topics

### ISSUE THREAD

**Issue by YiChenCityU** [HKUST-Aerial-Robotics/DenseSurfelMapping#12]
Hi, when I try this code on my own device (d435i), I met this problem. The depth msg cannot be received by surfel_fusion. I think the sync policy has some bug. Thanks very much. 
![Screenshot from 2019-09-03 17-20-08](https://user-images.githubusercontent.com/12424523/64161037-859f1d80-ce6f-11e9-83dd-97df13230513.png)

**Comment by WANG-KX** [comment]
It is hard to find if there are any bugs given only one image.
Could you provide more information?

**Comment by YiChenCityU** [comment]
I found that my data always has "image_time >pose_reference_time", which cause endless loop.

**Comment by WANG-KX** [comment]
well... You are using the ORB branch?
Also, the intrinsic parameter is very confusing. Are you sure the fx and fy are different so much? And cy is 237.3. What's the resolution of your depth camera?

**Comment by qmoji** [comment]
相机留在最后启动
