### ISSUE TITLE
Map accuracy evaluation tool

### ISSUE THREAD

**Issue by lvhualong** [HKUST-Aerial-Robotics/DenseSurfelMapping#13]
Hi,
 This really is very amazing work，it's  practical  in engineering.
 en, I want to know the evaluation tool of Map accuracy and Visualization Tools，to test my own data.
![image](https://user-images.githubusercontent.com/26672004/65406410-0ff4f480-de12-11e9-9b88-2db6ed300f5b.png)

**Comment by WANG-KX** [comment]
Hi, The tool is called CloudCompare.
