### ISSUE TITLE
Do we have to transform the pose as KITTI dataset if we use poses from other SLAM system?

### ISSUE THREAD

**Issue by YiChenCityU** [HKUST-Aerial-Robotics/DenseSurfelMapping#15]
Hi, Wang, I found that there is a transform dedicated for kitti. Is it needed for every SLAM system? Can I delete it? 

  static Eigen::Matrix4d transform_kitti;
    {
        Eigen::Matrix4d received_pose;
        pose_ros2eigen(input_pose, received_pose);        
        if(poses_database.size() == 0)
        {
            Eigen::Matrix4d idea_pose;
            idea_pose = Eigen::Matrix4d::Zero();
            idea_pose(0,0) = 1.0;
            idea_pose(1,2) = 1.0;
            idea_pose(2,1) = -1.0;
            idea_pose(3,3) = 1.0;
            transform_kitti = idea_pose * received_pose.inverse();
        }
        Eigen::Matrix4d transformed_pose;
        transformed_pose = transform_kitti * received_pose;
        pose_eigen2ros(transformed_pose, input_pose);
    }
    transform end

**Comment by WANG-KX** [comment]
If I remember correctly, the idea_pose is only for better visualization. 
Set it to Identity if you want.
