### ISSUE TITLE
能否离线建图？

### ISSUE THREAD

**Issue by fromyao** [HKUST-Aerial-Robotics/DenseSurfelMapping#17]
您好
        请问能不能直接根据已有的位姿，以及RGBD图像来建图呢？
如果能，那我需要对哪里进行修改呢？

**Comment by WANG-KX** [comment]
Hi, sorry I can't type in Chinese on the current computer.
Maybe you can write a warper and publish the known pose and RGB-D frames sequentially. Since you do not have a pose graph, the mapping cannot be fused looped surfels.
