### ISSUE TITLE
VINS-MONO for DenseSurfelMapping is open?

### ISSUE THREAD

**Issue by nonlinear1** [HKUST-Aerial-Robotics/DenseSurfelMapping#21]
I have tested the DenseSurfelMapping. I think it is very good. I have read this sentence " For VINS-MONO, we are using it in a teach-and-repeat project and will opensource lately". Do you have opened the source of VINS-MONO for DenseSurfelMapping for open source community? 
Thank you very much

**Comment by WANG-KX** [comment]
Just check out the branch ```VINS-supported```.
