### ISSUE TITLE
Uneven results for Reconstruction

### ISSUE THREAD

**Issue by qq1962572025** [HKUST-Aerial-Robotics/DenseSurfelMapping#23]
The reconstruction rsult is quiet uneven.As shown after,a small part of  the provided dataset is much better than others.
![细节](https://user-images.githubusercontent.com/40595559/74645961-dd2e0d00-51b3-11ea-9132-14c2b5df6bbd.png)
I'm curious why.

**Comment by WANG-KX** [comment]
It is very abnormal. 
From the image, I guess you are running KITTI. Seems the trajectory is right but the fusion is wrong. Have you visualized your depth map before fusion? And what's your method for depth map estimation.

**Comment by qq1962572025** [comment]
> It is very abnormal.
> From the image, I guess you are running KITTI. Seems the trajectory is right but the fusion is wrong. Have you visualized your depth map before fusion? And what's your method for depth map estimation.

I have found the reason.This is because I adopted the wrong image transfer method. I changed the transfer method in surfer_fusion to the ORB-SLAM2 method.
