### ISSUE TITLE
Having trouble running TUM dataset

### ISSUE THREAD

**Issue by qq1962572025** [HKUST-Aerial-Robotics/DenseSurfelMapping#24]
I want to run program on an indoor dataset to observe the result of the reconstruction. I modify the camera Intrinsic in the launch file for node surfer_fusion, and rewrite the node that sends the picture like this:
	    depth = cv::imread(PATH+s1, -1);
	    left = cv::imread(PATH+s2,-1);
	    cvtColor( left, left, CV_BGR2GRAY ); 
	    depth.convertTo(depth,CV_32F);
            sensor_msgs::ImagePtr msg_1 = cv_bridge::CvImage(std_msgs::Header(), "mono8", left).toImageMsg();
	    sensor_msgs::ImagePtr msg_2 = cv_bridge::CvImage(std_msgs::Header(), "32FC1", depth).toImageMsg();
ORB-SLAM2 runs well as usual,but surfer_fusion cannot create any surfel,is there other part of the program that should be modified?
![image](https://user-images.githubusercontent.com/40595559/74721752-d4e8d700-5272-11ea-80bf-e1061ea1f19f.png)

**Comment by qq1962572025** [comment]
The unit of the depth map in the code is meter, so TUM data needs to be divided by factor.

**Comment by allenthreee** [comment]
> 

can you give more details about the factor about TUM dataset, thank you

**Comment by canglangzhige** [comment]
> The unit of the depth map in the code is meter, so TUM data needs to be divided by factor.

您好，我也在尝试运行TUM的数据集。我没有写数据的发布节点，而是直接使用tum 的rosbag直接发布数据，我的运行结果如下：
![image](https://user-images.githubusercontent.com/48430568/168407749-e818d655-43dc-4b1d-8fba-1dc44ef285bd.png)
![image](https://user-images.githubusercontent.com/48430568/168407756-44680175-f87e-4cd2-80ee-8e9a8b4dd2bf.png)
但是orb的点云在rviz中显示不出来，显示为：
![image](https://user-images.githubusercontent.com/48430568/168407781-f3c061ec-142f-44b0-b0ae-98fbac4266ea.png)
运行surfel_fusion节点时，rviz没有出现任何surfel，我的几个终端显示：
![image](https://user-images.githubusercontent.com/48430568/168407805-88ac1de8-baa8-4721-9ec6-f51f534968cf.png)
按您说的，我在surfel_map.cpp文件中把深度图的单位进行了转换：
image.convertTo(image,CV_32F,mDepthMapFactor);
mDepthMapFactor 应该是取0.0002吧（5000我也试过），我看TUM的5000值对应距离1米，但还是不行，请问您有什么建议吗？
