### ISSUE TITLE
surfel map

### ISSUE THREAD

**Issue by Super-Iron-Man** [HKUST-Aerial-Robotics/DenseSurfelMapping#28]
您好，运行kitti数据集时没有问题，换做自己的realsense d435i相机后，运行surfel map时，程序没有继续执行，一直显示：
begin new frame process!!!
warp the surfels according to the loop!
warp end! cost 0.000224 ms.

**Comment by HeartFreeNo1** [comment]
我也和你一模一样的问题，你最后解决了没，我用的是realsense d435

**Comment by WANG-KX** [comment]
Hi,
I think this is a time synchronize problem. The depth, image from real sense may not be well synchronized. Check [this function](https://github.com/HKUST-Aerial-Robotics/DenseSurfelMapping/blob/77f65b1cfd3390ca50f1c94b1f0f250aeec2a00b/surfel_fusion/src/surfel_map.cpp#L103) to understand how the surfel mapping system synchronize all the messages.
