### ISSUE TITLE
Compilation problem with kitti_publisher

### ISSUE THREAD

**Issue by DYYYYYYYYY** [HKUST-Aerial-Robotics/DenseSurfelMapping#3]
Hello, when I catkin_make kitti_publisher, the following error occurred
Could not find a package configuration file provided by "depthnet_msgs"
   With any of the following names:

     depthnet_msgsConfig.cmake
     Depthnet_msgs-config.cmake
What is going on with this?

**Comment by WANG-KX** [comment]
remove the line 17 from the CMakeLists.txt of the kitti_publisher. I have removed it and updated.
