### ISSUE TITLE
利用PSMNET生成kitti_odometry_00的深度图像，最大深度是128。然后利用vins-fusion进行该算法的测试，结果非常不好，不知道什么原因？

### ISSUE THREAD

**Issue by yueshukun** [HKUST-Aerial-Robotics/DenseSurfelMapping#30]
具体测试截图如下：
![Screenshot from 2020-05-19 11-17-39](https://user-images.githubusercontent.com/30314477/82295932-0775ad80-99e3-11ea-9102-129e9b3ec2b0.png)
![Screenshot from 2020-05-19 11-19-53](https://user-images.githubusercontent.com/30314477/82295941-0ba1cb00-99e3-11ea-8185-9f22be4d39b4.png)
生成的深度图如下：
![000000](https://user-images.githubusercontent.com/30314477/82295973-1bb9aa80-99e3-11ea-946a-e11f6266a968.png)
求高手解答，谢谢！

**Comment by WANG-KX** [comment]
The result fro PSMNet is a disparity map. Convert to depth maps (meters) before any usage.

**Comment by 708949503** [comment]
您好，请问您之前提出的那个问题解决了吗？
OpenCV Error: Assertion failed (0 <= _rowRange.start && _rowRange.start <= _rowRange.end && _rowRange.end <= m.rows)

**Comment by zheng-xiao** [comment]
请问，您的视差图还保存着吗？我使用PMSNet生成的视差图精度不好

**Comment by zheng-xiao** [comment]
如果还保存，可以分享给我一份吗？我的邮箱是1287595254@qq.com。非常感谢
