### ISSUE TITLE
problem when running on the ICL-NUIM dataset

### ISSUE THREAD

**Issue by louzq16** [HKUST-Aerial-Robotics/DenseSurfelMapping#36]
Thank for your nice work!
I would like to reproduce the result on ICL-NUIM dataset of DSM in the paper.
I choose sequence living_room_traj0n_frei as test sequence. ORB-SLAM2 works well in RGBD mode, but surfel_fusion died.
the launch file is as follows:
![image](https://user-images.githubusercontent.com/44044820/96401172-3b106a00-1205-11eb-8aed-bbb8c152573f.png)
After tracking the errors, I found that the position where the problem occured:
![image](https://user-images.githubusercontent.com/44044820/96401396-bffb8380-1205-11eb-9337-0f4c6b482921.png)
When fusing surfels, the variable sp_index sometimes is -1 which is out of range. 
I'd like to know whether if it is normal that the superpixel index is -1 after superpixel segmentation in DSM. Or there exists some errors in my parameter setting?

**Comment by LeeYing97** [comment]
How can your ORB-SLAM2 work well in RGBD mode with the noise sequence of ICL-NUIM? I only can do it with the sequence without noise.
