### ISSUE TITLE
How to evaluate

### ISSUE THREAD

**Issue by zhangxrr** [HKUST-Aerial-Robotics/DenseSurfelMapping#38]

**Comment by zhangxrr** [comment]
Hi, Mr Wang ,could you please tell me how to evaluate the dense surfel mapping on VINS-MONO?Are there any benchmark about the 3D reconstruction on SLAM with imu and carema?

**Comment by WANG-KX** [comment]
Hi,
The EUROC dataset is useful for you. But you need to register the Lidar points and your reconstruction/camera pose before the evaluation. I don't know how, but there are papers doing so.
