### ISSUE TITLE
rviz always crashes

### ISSUE THREAD

**Issue by DYYYYYYYYY** [HKUST-Aerial-Robotics/DenseSurfelMapping#4]
Hello, rviz always crashes when I load rviz_config.rviz in the last step. Why is this?

**Comment by DYYYYYYYYY** [comment]
When I loaded rviz_config.rviz, the following error occurred after rviz crashed.

terminate called after throwing an instance of 'Ogre::InternalErrorException'
  what():  OGRE EXCEPTION(7:InternalErrorException): Cannot create GL vertex buffer in GLHardwareVertexBuffer::GLHardwareVertexBuffer at /build/ogre-1.9-mqY1wq/ogre-1.9-1.9.0+dfsg1/RenderSystems/GL/src/OgreGLHardwareVertexBuffer.cpp (line 47)

**Comment by WANG-KX** [comment]
Hello,
How about you manually add the topic from dense_surfel_mapping? And what's your ubuntu, ROS, and RVIZ version?

**Comment by DYYYYYYYYY** [comment]
I open rviz via rosrun rqt_rviz rqt_rviz and load rviz_config.rviz with the open config option.
My ROS version is
 * /rosdistro: kinetic
  * /rosversion: 1.12.14
My rviz version is
[ INFO] [1557975521.968744314]: rviz version 1.12.17
[ INFO] [1557975521.968783295]: compiled against Qt version 5.5.1
[ INFO] [1557975521.968793213]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1557975522.102393911]: Stereo is NOT SUPPORTED
[ INFO] [1557975522.102473766]: OpenGl version: 3 (GLSL 1.3).

**Comment by WANG-KX** [comment]
Try
```rviz rviz_config.rviz``` ?

**Comment by DYYYYYYYYY** [comment]
Do I manually add a topic after I open it? In addition, my computer does not have a GPU. Does this matter?

**Comment by WANG-KX** [comment]
Have you already run the code and then launch the rviz? Or just launch the rviz and it crashes?

**Comment by DYYYYYYYYY** [comment]
The picture after I manually added the topic is as follows, and it is different from the dense picture in the demo.
![398c830f96f0b1cbe006c177d8bbfe9](https://user-images.githubusercontent.com/48936737/57826957-0e6a4e80-77d8-11e9-9fe7-19620c221730.png)

**Comment by DYYYYYYYYY** [comment]
I followed the order you wrote, and finally opened rviz.

**Comment by luzhaozhang2276** [comment]
@WANG-KX  @DYYYYYYYYY 
你好,请问我在最后一步运行`rviz rviz_config.rviz`命令后,rviz里的Fixed Frame出现了错误,rviz画面里也没有地图的更新信息,请问你知道怎么解决吗?
![image](https://user-images.githubusercontent.com/43841773/64902897-93139d80-d6e2-11e9-9ca7-7a930240e0f7.png)

**Comment by DYYYYYYYYY** [comment]
@luzhaozhang2276 尝试把Global Options 里的Fixed Frame 改成 world试试看
