### ISSUE TITLE
Using SGM

### ISSUE THREAD

**Issue by RamadanAhmed** [HKUST-Aerial-Robotics/DenseSurfelMapping#40]
Hi,
Thanks for the project, I want to ask if I can use sgm from https://github.com/fixstars/libSGM to calculate disparity maps or there is certain methods that should be used

**Comment by WANG-KX** [comment]
hi, sorry for the late reply.
Any depth estimation method can be used for map fusion. The better the depth, the better the map you can get.
Regarding SGM, I'm not sure how good this "libsgm" is. If the disparity you get is discrete, I don't think the quality can be good.

**Comment by RamadanAhmed** [comment]
Thanks for answering,
I didn't try it yet, but I was asking if there are any constraints/methods that should be applied before using other depth estimation techniques
