### ISSUE TITLE
where does the depth information come from in VINS-MONO-SUPPORT?

### ISSUE THREAD

**Issue by HeadReaper-hc** [HKUST-Aerial-Robotics/DenseSurfelMapping#42]
Hi,
     I see the code **_remap from="~depth" to="/camera/aligned_depth_to_color/image_raw_**  in vins_realsense.launch file,
so does this mean the depth information is directly come from the camera sensor, not computed by adjacent images?

**Comment by WANG-KX** [comment]
yes, any RGB-D camera or stereo rig can be used, as long as the depth quality is acceptable.

**Comment by HeadReaper-hc** [comment]
@WANG-KX Got it. Thanks.
