### ISSUE TITLE
Some data

### ISSUE THREAD

**Issue by Weiyinyin11** [HKUST-Aerial-Robotics/DenseSurfelMapping#46]
Hello, Dr. Wang, I saw on the author's Github of MMGCN that you reproduced the paper and raised some questions to the author at that time. Do you still have the data set of that paper?Can you share it with me?

**Comment by WANG-KX** [comment]
I do not have the data.

**Comment by Weiyinyin11** [comment]
Ok, thanks for your reply

**Comment by Weiyinyin11** [comment]
> I do not have the data.

Ok, thanks for your reply
