### ISSUE TITLE
I can't open the saved PLY file with CloudCompare. What is the reason?

### ISSUE THREAD

**Issue by hululuhu** [HKUST-Aerial-Robotics/DenseSurfelMapping#5]

**Comment by hululuhu** [comment]
The reason is that the PLY file is incompletely saved. Press crtl + c to exit the process and save the PLY file. Because the PLY file is large, the PLY file will be saved incompletely.

**Comment by WANG-KX** [comment]
Are you pressing ctrl+c for many times before the saving finishes? Actually, I don't know any other methods to "save the map before quitting". Maybe adding a ROS SERVICE to save is a good option.

**Comment by WANG-KX** [comment]
Just notice in my code, that it actually support saving PLY file when you publish a rostopic called "save_map" with string msg. Check the code here: https://github.com/HKUST-Aerial-Robotics/DenseSurfelMapping/blob/c9e32e2b14b3028e8f7491524bf924dc9bd32534/surfel_fusion/src/ros_node.cpp#L26
