### ISSUE TITLE
Question about dataset of DenseSurfelMapping

### ISSUE THREAD

**Issue by canglangzhige** [HKUST-Aerial-Robotics/DenseSurfelMapping#51]
Your work is great and I would like to learn it. But when downloading the KITTI dataset you gave it shows that the link does not exist. Is this dataset different from the KITTI official website? There are only stereo images on the official website. The KITTI connection you gave should contain depth values, right? Could you please send me a copy, thanks!

**Comment by zheng-xiao** [comment]
Do you have a depth map now? If you have, could you share with me?

**Comment by WANG-KX** [comment]
It's the same with the official kitti dataset.
You can generate your own depth maps using state-of-the-are stereo matching methods.
