### ISSUE TITLE
Hello! When is open source based on DenseSurfelMapping source code for VINS-MONO?

### ISSUE THREAD

**Issue by hululuhu** [HKUST-Aerial-Robotics/DenseSurfelMapping#6]

**Comment by WANG-KX** [comment]
Hi!
I have put the code on the branch ```VINS-supported```, but it is still a mess:sweat_smile:
I will try my best to clean the code this weekend.
Hope it can benefit your project!
Kaixuan

**Comment by hululuhu** [comment]
Thank you very much for your reply！
