### ISSUE TITLE
about depth scale

### ISSUE THREAD

**Issue by AdamAsh2019** [HKUST-Aerial-Robotics/DenseSurfelMapping#7]
hi thanks for releasing your wonderful work! the depth map come from PSMnet as mentioned in introduction page. I wonder have you ever post-processed the depth of PSMnet such as re-scale or you just  directly take the output of PSMnet as depth.

**Comment by WANG-KX** [comment]
The PSMnet is a stereo method that generates disparity maps from stereo images. I converted the disparity maps into depth maps for fusion.

**Comment by AdamAsh2019** [comment]
@WANG-KX thanks for replying, did you directly use the pretained weights on official PSMnet github site or you trained the PSMnet for your own dataset.

**Comment by WANG-KX** [comment]
I used the official one from Github.
